#!/usr/bin/env ruby

require 'csv'
require 'json'

trips = []

CSV.foreach('trips.csv', quote_char: '"', col_sep: ',', row_sep: :auto, headers: true) do |row|
  # https://www.mapbox.com/base/styling/icons/
  marker_symbol =
    case row[4]
    when /run/i, /hike/i
      'pitch'
    when /business/i
      'suitcase'
    when /tourism/i
      'museum'
    when /swim/i, /scuba diving/i
      'swimming'
    else
      'marker'
    end

  trip = {
    'type': 'Feature',
    'geometry': {
      'type': 'Point',
      'coordinates': [
        # latitude then longitude, cuz GeoJson
        row[3],
        row[2]
      ]
    },
    'properties': {
      'Date': row[0],
      'Location': row[1],
      'Note': row[4],
      'marker-size': 'small',
      'marker-symbol': marker_symbol,
      'marker-color': '#3887be'
    }
  }

  trips << trip
end

trips = {
  'type': 'FeatureCollection',
  'features': trips
}

begin
  file = File.open('trips.geojson', 'w')
  file.puts trips.to_json
rescue IOError => e
  puts "Something went wrong: #{e}"
ensure
  file.close unless file&.nil?
end
